<tr>
	<td class="info_head"><span class="right">{CACHE}</span>{L_SN_STATSCOUNTER}</td>
</tr>
<tr>
	<td>{SC_TODAY}</td>
</tr>
<tr>
	<td>{SC_YESTERDAY}</td>
</tr>
<tr>
	<td>{SC_MONTH}</td>
</tr>
<tr>
	<td>{SC_YEAR}</td>
</tr>
<tr>
	<td>{SC_TOTAL}</td>
</tr>
<tr>
	<td>&nbsp;</td>
</tr>